#!/usr/bin/env sh
[ "$POB_GIT_HOOKS" = "2" ] && set -x
[ "$POB_GIT_HOOKS" = "0" ] && exit 0
[ "$HUSKY" = "0" ] && exit 0

if [ -n "$(git diff HEAD@{1}..HEAD@{0} -- bun.lock)" ] | [ "$1" = "rebase" ]; then
  bun i --frozen-lockfile || true
fi
